Neos:
  GoogleAnalytics:
    authentication:
      applicationName: 'Neos GA'
      clientId: '4730774009-h57rl51jmjbrljt2mii1ebn74a8hsrr3.apps.googleusercontent.com'
      clientSecret: '%env:GA_SECRET%'
      developerKey: '%env:GA_DEVKEY%'
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'smtp-broadcasts.postmarkapp.com'
        port: '587'
        encryption: 'tls'
        username: '%env:SFI_PM_USER%'
        password: '%env:SFI_PM_PASSWORD%'
  Flow:
    http:
      baseUri: 'https://sfi.ru/'
    log:
      systemLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
      securityLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
      sqlLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
      i18nLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
    error:
      exceptionHandler:
        className: 'Yeebase\Graylog\Error\GraylogExceptionHandler'
Yeebase:
  Graylog:
    host: 'graylog'
    port: 12201
    chunksize: 'wan'
