Neos:
  GoogleAnalytics:
    authentication:
      applicationName: 'Neos GA'
      clientId: '4730774009-h57rl51jmjbrljt2mii1ebn74a8hsrr3.apps.googleusercontent.com'
      clientSecret: '%env:GA_SECRET%'
      developerKey: '%env:GA_DEVKEY%'
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'smtp-broadcasts.postmarkapp.com'
        port: '587'
        encryption: 'tls'
        username: '%env:SFI_PM_USER%'
        password: '%env:SFI_PM_PASSWORD%'
  Flow:
    http:
      baseUri: 'https://sfi.ru/'
    chunksize: 'wan'
